Revert "Add productservices to super partition"
This reverts commit 4ad4433be3760aee1837f09ff8622f4ff5fa051e.

Reason for revert: To fix blueline_mainline-userdebug

Build log snippet:
++++ product-services ++++
creating product-services.img...
Traceback (most recent call last):
File "build/make/tools/releasetools/add_img_to_target_files", line 827, in <module>
main(sys.argv[1:])
File "build/make/tools/releasetools/add_img_to_target_files", line 821, in main
AddImagesToTargetFiles(args[0])
File "build/make/tools/releasetools/add_img_to_target_files", line 739, in AddImagesToTargetFiles
partitions['product-services'] = AddProductServices(output_zip)
File "build/make/tools/releasetools/add_img_to_target_files", line 213, in AddProductServices
block_list=block_list)
File "build/make/tools/releasetools/add_img_to_target_files", line 299, in CreateImage
assert succ, "build " + what + ".img image failed"
AssertionError: build product-services.img image failed
ninja: build stopped: subcommand failed.
19:16:28 ninja failed with: exit status 1
make: *** [run_soong_ui] Error 1
Return Code: 2

Change-Id: I967bb3942f6cfe36b77c42e96640af8e039343c4