Remove dup file_contexts label
/dev/input(/.*)? u:object_r:input_device:s0

Is now in core policy. Remove from device specific policy.

Fixes build error:
out/target/product/crosshatch/obj/ETC/file_contexts.bin_intermediates/file_contexts.concat.tmp:
Multiple same specifications for /dev/input(/.*)?.
Error: could not load context file from
out/target/product/crosshatch/obj/ETC/file_contexts.bin_intermediates/file_contexts.concat.tmp

Bug: 64954704
Bug: 65038865
Test: build
Change-Id: I5f72ff34a7332365e434ddf0dbb5b0ac02c71448